### PR TITLE
Remove wallet from GetRequiredFee

### PR DESCRIPTION
**Pull request by mderasse**
Fix build issue

We need to do the same for 0.16 as that one cannot automatically merge ...

### CODE REVIEW

**Comment by hd4r** [comment]
Is this necessary or just to clean up an unused variable?

**Comment by mderasse** [comment]
We have to make a choice between pass the wallet in the code of your last pull request or do that,
Following your last PR the code doesn't compile anymore

Btw, it's actually only impact the 0.19 :)

**Comment by hd4r** [comment]
Oh sorry, I only tested it in 0.16. Why does it not compile in 0.19? Because of the unused variable?

**Comment by mderasse** [comment]
because you are calling : return GetRequiredFee(nTxBytes);
and in the 0.19 GetRequiredFee need the wallet in first params

**Comment by hd4r** [comment]
Oh right. Perhaps we should change this to GetRequiredFee(wallet, nTxBytes)? Just to stay closer to the bitcoin code.

**Comment by mderasse** [comment]
Fine to me :) will do that after work

**Pull request closed without merging**
