### PR TITLE
Disable test by default and let user enable it throught configure

### PR DESCRIPTION
**Pull request by mderasse**

### CODE REVIEW

**Comment by hd4r** [comment]
Can you comment why you want to disable tests by default?

**Comment by mderasse** [comment]
I'm not a huge fan but look like it was done like that on the 0.16 ...

**Comment by hd4r** [comment]
Is this about tests such as unit tests that run while building the code?

**Comment by mderasse** [comment]
It's the compilation of test_verium and test_verium-qt. But i guess some of those test are already not working since they was made for btc and we did a quite number of change :)

**Comment by hd4r** [comment]
@effectsToCause can you comment why this was disabled in 0.16?

**Comment by effectsToCause** [comment]
I think I disabled while doing some work on 0.16 just for convenience as at the time there was some changes needed to the tests.

**Comment by effectsToCause** [comment]
We can reenable by default if you guys like but I think the tests need some work still.

**Comment by hd4r** [comment]
What kinds of tests are those?

**Comment by effectsToCause** [comment]
For simplicity of testing main client first and not building many tests each compile I will disable for now but at release we can run tests and re-enable default compile

**Comment by mderasse** [comment]
Ok, maybe create a trello task ? After i'm sure we will have to iterate since all the test will not pass :p

**Comment by effectsToCause** [comment]
yeah sounds good.

**Pull request merged**
